spring.application.name=patient-management
# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://smartcarestaging.database.windows.net:1433;database=smartcare-patient-service;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Server Configuration
server.port=8091
