apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management-deployment-staging
  labels:
    app: patient-management-deployment-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-management-deployment-staging
  template:
    metadata:
      name: patient-management-deployment-staging
      labels:
        app: patient-management-deployment-staging
    spec:
      containers:
        - name: patient-management-deployment-staging
          env:
            - name: ENV_PROFILE
              value: prod
          image: smartcare.azure.io/patient-management-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      