apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-management-deployment-staging
  labels:
    app: patient-management-deployment-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patient-management-deployment-staging
  template:
    metadata:
      name: patient-management-deployment-staging
      labels:
        app: patient-management-deployment-staging
    spec:
      containers:
        - name: patient-management-deployment-staging
          env:
            - name: ENV_PROFILE
              value: staging
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: AZURE_DB_USERNAME
                  name: smartcare-patient-management-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AZURE_DB_PASSWORD
                  name: smartcare-patient-management-secrets
          image: smartcare.azurecr.io/smartcare-patient-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      