apiVersion: v1
kind: Service
metadata:
  name: patient-management-deployment-service
spec:
  selector:
    app: patient-management-deployment-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  